// @ts-check
// The sidebar is generated from the docs/ folder tree. Ordering and category
// labels come from `_category_.json` files and per-doc `sidebar_position`
// frontmatter. See https://docusaurus.io/docs/sidebar/autogenerated

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};

module.exports = sidebars;
